import { Theme, ThemeName } from '../types/theme';

export const themes: Record<ThemeName, Theme> = {
  light: {
    name: 'light',
    isDark: false,
    colors: {
      name: 'light',
      label: 'Light',
      bg: 'bg-gray-50',
      bgSecondary: 'bg-white',
      sidebar: 'bg-white',
      card: 'bg-white',
      cardHover: 'hover:bg-gray-50',
      primary: 'bg-blue-600',
      primaryHover: 'hover:bg-blue-700',
      primaryText: 'text-white',
      text: 'text-gray-900',
      textSecondary: 'text-gray-700',
      textMuted: 'text-gray-500',
      border: 'border-gray-200',
      borderLight: 'border-gray-100',
      accent: 'text-blue-600',
      accentHover: 'hover:text-blue-700',
      success: 'text-green-500',
      warning: 'text-yellow-500',
      error: 'text-red-500',
      info: 'text-blue-500',
      inputBg: 'bg-white',
      inputBorder: 'border-gray-300',
      inputFocus: 'focus:border-blue-500'
    }
  },
  dark: {
    name: 'dark',
    isDark: true,
    colors: {
      name: 'dark',
      label: 'Dark',
      bg: 'bg-gray-900',
      bgSecondary: 'bg-gray-800',
      sidebar: 'bg-gray-800',
      card: 'bg-gray-800',
      cardHover: 'hover:bg-gray-700',
      primary: 'bg-blue-500',
      primaryHover: 'hover:bg-blue-600',
      primaryText: 'text-white',
      text: 'text-white',
      textSecondary: 'text-gray-200',
      textMuted: 'text-gray-400',
      border: 'border-gray-700',
      borderLight: 'border-gray-600',
      accent: 'text-blue-400',
      accentHover: 'hover:text-blue-300',
      success: 'text-green-500',
      warning: 'text-yellow-500',
      error: 'text-red-500',
      info: 'text-blue-500',
      inputBg: 'bg-gray-700',
      inputBorder: 'border-gray-600',
      inputFocus: 'focus:border-blue-400'
    }
  },
  ocean: {
    name: 'ocean',
    isDark: true,
    colors: {
      name: 'ocean',
      label: 'Ocean',
      bg: 'bg-slate-900',
      bgSecondary: 'bg-slate-800',
      sidebar: 'bg-slate-800',
      card: 'bg-slate-800',
      cardHover: 'hover:bg-slate-700',
      primary: 'bg-teal-500',
      primaryHover: 'hover:bg-teal-600',
      primaryText: 'text-white',
      text: 'text-white',
      textSecondary: 'text-slate-200',
      textMuted: 'text-slate-400',
      border: 'border-slate-700',
      borderLight: 'border-slate-600',
      accent: 'text-teal-400',
      accentHover: 'hover:text-teal-300',
      success: 'text-green-500',
      warning: 'text-yellow-500',
      error: 'text-red-500',
      info: 'text-blue-500',
      inputBg: 'bg-slate-700',
      inputBorder: 'border-slate-600',
      inputFocus: 'focus:border-teal-400'
    }
  },
  sunset: {
    name: 'sunset',
    isDark: false,
    colors: {
      name: 'sunset',
      label: 'Sunset',
      bg: 'bg-orange-50',
      bgSecondary: 'bg-white',
      sidebar: 'bg-white',
      card: 'bg-white',
      cardHover: 'hover:bg-orange-50',
      primary: 'bg-orange-500',
      primaryHover: 'hover:bg-orange-600',
      primaryText: 'text-white',
      text: 'text-gray-900',
      textSecondary: 'text-gray-700',
      textMuted: 'text-gray-500',
      border: 'border-orange-200',
      borderLight: 'border-orange-100',
      accent: 'text-orange-600',
      accentHover: 'hover:text-orange-700',
      success: 'text-green-500',
      warning: 'text-yellow-500',
      error: 'text-red-500',
      info: 'text-blue-500',
      inputBg: 'bg-white',
      inputBorder: 'border-orange-300',
      inputFocus: 'focus:border-orange-500'
    }
  },
  forest: {
    name: 'forest',
    isDark: true,
    colors: {
      name: 'forest',
      label: 'Forest',
      bg: 'bg-emerald-950',
      bgSecondary: 'bg-emerald-900',
      sidebar: 'bg-emerald-900',
      card: 'bg-emerald-900',
      cardHover: 'hover:bg-emerald-800',
      primary: 'bg-emerald-500',
      primaryHover: 'hover:bg-emerald-600',
      primaryText: 'text-white',
      text: 'text-white',
      textSecondary: 'text-emerald-100',
      textMuted: 'text-emerald-300',
      border: 'border-emerald-800',
      borderLight: 'border-emerald-700',
      accent: 'text-emerald-400',
      accentHover: 'hover:text-emerald-300',
      success: 'text-green-500',
      warning: 'text-yellow-500',
      error: 'text-red-500',
      info: 'text-blue-500',
      inputBg: 'bg-emerald-800',
      inputBorder: 'border-emerald-700',
      inputFocus: 'focus:border-emerald-400'
    }
  },
  royal: {
    name: 'royal',
    isDark: true,
    colors: {
      name: 'royal',
      label: 'Royal',
      bg: 'bg-purple-950',
      bgSecondary: 'bg-purple-900',
      sidebar: 'bg-purple-900',
      card: 'bg-purple-900',
      cardHover: 'hover:bg-purple-800',
      primary: 'bg-purple-500',
      primaryHover: 'hover:bg-purple-600',
      primaryText: 'text-white',
      text: 'text-white',
      textSecondary: 'text-purple-100',
      textMuted: 'text-purple-300',
      border: 'border-purple-800',
      borderLight: 'border-purple-700',
      accent: 'text-purple-400',
      accentHover: 'hover:text-purple-300',
      success: 'text-green-500',
      warning: 'text-yellow-500',
      error: 'text-red-500',
      info: 'text-blue-500',
      inputBg: 'bg-purple-800',
      inputBorder: 'border-purple-700',
      inputFocus: 'focus:border-purple-400'
    }
  }
};

export const getTheme = (name: ThemeName): Theme => themes[name];
export const getAllThemes = (): Theme[] => Object.values(themes);